#ifndef DMF_VERIFIER_H
#define DMF_VERIFIER_H

/* Generated by flatcc 0.4.1 FlatBuffers schema compiler for C by dvide.com */

#ifndef DMF_READER_H
#include "dmf_reader.h"
#endif
#include "flatcc/flatcc_verifier.h"
#define PDIAGNOSTIC_IGNORE_UNUSED
#include "flatcc/portable/pdiagnostic_push.h"

static int __dmf_Material_table_verifier(flatcc_table_verifier_descriptor_t *td);
static int __dmf_Shape_table_verifier(flatcc_table_verifier_descriptor_t *td);
static int __dmf_Model_table_verifier(flatcc_table_verifier_descriptor_t *td);

static inline int dmf_Vec2_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, dmf_Vec2_identifier, 4, 8);
}

static inline int dmf_Vec2_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, dmf_Vec2_type_hash, 4, 8);
}

static inline int dmf_Vec2_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, thash, 4, 8);
}

static inline int dmf_Vec2_verify_as_root_with_identifer(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, fid, 4, 8);
}

static inline int dmf_Vec3_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, dmf_Vec3_identifier, 4, 12);
}

static inline int dmf_Vec3_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, dmf_Vec3_type_hash, 4, 12);
}

static inline int dmf_Vec3_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, thash, 4, 12);
}

static inline int dmf_Vec3_verify_as_root_with_identifer(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, fid, 4, 12);
}

static inline int dmf_Color_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, dmf_Color_identifier, 4, 12);
}

static inline int dmf_Color_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, dmf_Color_type_hash, 4, 12);
}

static inline int dmf_Color_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, thash, 4, 12);
}

static inline int dmf_Color_verify_as_root_with_identifer(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, fid, 4, 12);
}

static int __dmf_Material_table_verifier(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_string_field(td, 0, 0) /* name */)) return ret;
    if ((ret = flatcc_verify_field(td, 1, 4, 12) /* ambient */)) return ret;
    if ((ret = flatcc_verify_field(td, 2, 4, 12) /* diffuse */)) return ret;
    if ((ret = flatcc_verify_field(td, 3, 4, 12) /* specular */)) return ret;
    if ((ret = flatcc_verify_field(td, 4, 4, 4) /* shininess */)) return ret;
    if ((ret = flatcc_verify_field(td, 5, 4, 4) /* dissolve */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 6, 0) /* ambient_map */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 7, 0) /* diffuse_map */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 8, 0) /* specular_map */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 9, 0) /* bump_map */)) return ret;
    return flatcc_verify_ok;
}

static inline int dmf_Material_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, dmf_Material_identifier, &__dmf_Material_table_verifier);
}

static inline int dmf_Material_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, dmf_Material_type_identifier, &__dmf_Material_table_verifier);
}

static inline int dmf_Material_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &__dmf_Material_table_verifier);
}

static inline int dmf_Material_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &__dmf_Material_table_verifier);
}

static int __dmf_Shape_table_verifier(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_string_field(td, 0, 0) /* name */)) return ret;
    if ((ret = flatcc_verify_table_field(td, 1, 0, &__dmf_Material_table_verifier) /* material */)) return ret;
    if ((ret = flatcc_verify_vector_field(td, 2, 0, 4, 12, 357913941ULL) /* vertices */)) return ret;
    if ((ret = flatcc_verify_vector_field(td, 3, 0, 4, 12, 357913941ULL) /* normals */)) return ret;
    if ((ret = flatcc_verify_vector_field(td, 4, 0, 4, 8, 536870911ULL) /* texcoords */)) return ret;
    return flatcc_verify_ok;
}

static inline int dmf_Shape_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, dmf_Shape_identifier, &__dmf_Shape_table_verifier);
}

static inline int dmf_Shape_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, dmf_Shape_type_identifier, &__dmf_Shape_table_verifier);
}

static inline int dmf_Shape_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &__dmf_Shape_table_verifier);
}

static inline int dmf_Shape_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &__dmf_Shape_table_verifier);
}

static int __dmf_Model_table_verifier(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_table_vector_field(td, 0, 0, &__dmf_Shape_table_verifier) /* shapes */)) return ret;
    return flatcc_verify_ok;
}

static inline int dmf_Model_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, dmf_Model_identifier, &__dmf_Model_table_verifier);
}

static inline int dmf_Model_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, dmf_Model_type_identifier, &__dmf_Model_table_verifier);
}

static inline int dmf_Model_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &__dmf_Model_table_verifier);
}

static inline int dmf_Model_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &__dmf_Model_table_verifier);
}

#include "flatcc/portable/pdiagnostic_pop.h"
#endif /* DMF_VERIFIER_H */
